name: linting, build, testing
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run Eslint
        run: npm run ts:lint

      - name: Run Stylelint
        run: npm run scss:lint

      - name: Run Build
        run: npm run build

      - name: Run Unit test
        run: npm run test:unit