name: linting, build, testing
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    strategy:
      matrix:
        node: [12]
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Eslint
        run: npm run ts:lint

      - name: Run Stylelint
        run: npm run scss:lint

      - name: Run Build
        run: npm run build

      - name: Run Unit test
        run: npm test:unit